# Generated by Django 5.2.3 on 2025-06-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionPaypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_id', models.CharField(max_length=250)),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('invoice', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('payer_status', models.CharField(max_length=250)),
                ('payer_email', models.CharField(max_length=250)),
                ('txn_id', models.CharField(max_length=250)),
                ('receiver_id', models.CharField(max_length=250)),
                ('payment_gross', models.FloatField()),
                ('custom', models.CharField(max_length=250)),
            ],
        ),
    ]
