# Generated by Django 5.2.3 on 2025-06-27 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaypal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionpaypal',
            name='residence_country',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
