# Generated by Django 5.2.3 on 2025-06-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miPaypal', '0002_transaccionpaypal_residence_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccionpaypal',
            name='residence_country',
        ),
    ]
