# Generated by Django 5.2.3 on 2025-06-29 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaypal', '0006_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución'), ('dano', 'Producto Dañado'), ('vencimiento', 'Vencimiento')], max_length=20)),
                ('reason', models.CharField(choices=[('compra', 'Compra a proveedor'), ('venta', 'Venta a cliente'), ('reabastecimiento', 'Reabastecimiento'), ('inventario', 'Ajuste por inventario'), ('dano', 'Productos dañados'), ('vencimiento', 'Productos vencidos'), ('devolucion_cliente', 'Devolución de cliente'), ('devolucion_proveedor', 'Devolución a proveedor'), ('transferencia', 'Transferencia entre bodegas'), ('perdida', 'Pérdida o robo'), ('otro', 'Otro motivo')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miPaypal.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='miPaypal.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
