# Generated by Django 5.2.3 on 2025-06-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaypal', '0007_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
    ]
