# Generated by Django 5.2.3 on 2025-06-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaypal', '0008_customuser_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Retiro en Tienda'), ('delivery', 'Delivery a Domicilio')], default='pickup', max_length=20, verbose_name='Método de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
